repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: format-fix
        name: Formatting (ruff)
        entry: uv run ruff format .
        language: system
        types: [python]
        stages: [pre-commit]
      - id: lint-check
        name: Linting (ruff)
        entry: uv run ruff check . --fix
        language: system
        types: [python]
        stages: [pre-commit]
      - id: type-check
        name: Type checking (mypy)
        entry: uv run mypy .
        pass_filenames: false
        language: system
        types: [python]
        stages: [pre-commit]
      - id: test
        name: Unit testing (pytest)
        entry: uv run pytest
        pass_filenames: false
        language: system
        types: [python]
        stages: [pre-push]
